### ISSUE TITLE
Method for Image Reduction

### ISSUE THREAD

**Issue by vinoroidski** [hochschule-darmstadt/openartbrowser-social#5]
Some images for entities are quite large and there is a limitation for uploading to twitter.

@ahmadf0311: please post details (max dimensions or size) the image can be and comment that you have implemented this method so that we can close this ticket.

**Comment by ahmadf0311** [comment]
There is no ability to send photos larger than 3MB on Twitter. Since a photo may be larger than this size, a method is needed to make the photo smaller by a certain size. 
limit_img_size does some iterative resizing and jpeg compression of an image to then look at the resulting file size and compare it to a target value, guessing the next best width/height combination from the size deviation ratio
