### ISSUE TITLE
Create constant file

### ISSUE THREAD

**Issue by vinoroidski** [hochschule-darmstadt/openartbrowser-social#8]
This file includes all parameters which are constant for our application.
@ahmadf0311 : please add details and close issue.

**Comment by ahmadf0311** [comment]
Our constants include a Url of Openartbowser API and a count that indicates the number of Artworks to be included in the posting list.
We set a limit(image_processing_limit) to ignore photos above this range. The main reason for this is that the limit_img_size method does not have the ability to reduce a photo above a certain limit Due to buffering limitations.

In addition, Twitter does not allow photos to be posted above 3,072,000 KB. For this reason, limit_img_size is defined to reduce this amount to tweet_max_size in case of high volume of the photo.

One more constant with filepath for staging server has been added.

artwork_query  is a request that is sent to API to return a certain number of Artworks according to the descending relativeRank
